# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "bygning-github-workflows"
  tags:
  - "private"
spec:
  type: "service"
  lifecycle: "production"
  owner: "bygning"
  system: "matrikkel"
