name: Update App Version

on:
  workflow_call:
    inputs:
      application_name:
        description: "The name of the application"
        required: true
        type: string
      namespace_from:
        description: "Namespace in which the correct version currently runs"
        required: true
        type: string
      namespace_to:
        description: "Namespace to bump to"
        required: true
        type: string
      env_from:
        description: "The environment to bump from"
        required: true
        type: string
      env_to:
        description: "The environment to bump to"
        required: true
        type: string

permissions:
  id-token: write

jobs:
  update-app-version:
    runs-on: ubuntu-latest
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f
        id: octo-sts
        with:
          scope: kartverket/bygning-apps
          identity: bygning

      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          repository: kartverket/bygning-apps
          ref: main
          token: ${{ steps.octo-sts.outputs.token }}

      - name: Update version, commit and push
        run: |
          git config --global user.email "bygning@kartverket.no"
          git config --global user.name "Bygning CI"
          git pull

          cp env/atkv3-${{ inputs.env_from }}/${{ inputs.namespace_from }}/${{ inputs.application_name }}-version env/atkv3-${{ inputs.env_from }}/${{ inputs.namespace_to }}/${{ inputs.application_name }}-version

          git add .
          git commit -m "Bump version for application: ${{ inputs.application_name }}"
          git push
