name: Promote App Version

on:
  workflow_call:
    inputs:
      application_name:
        description: "The name of the application"
        required: true
        type: string
      namespace_from:
        description: "Namespace to promote from"
        required: true
        type: string
      namespace_to:
        description: "Namespace to promote to"
        required: true
        type: string
      cluster_from:
        description: "The cluster to promote from"
        required: true
        type: string
      cluster_to:
        description: "The cluster to promote to"
        required: true
        type: string
      allow_unsafe_deploy:
        description: "Whether or not applications can be deployed with image tags that are considered unsafe"
        type: boolean
        default: false
        required: false

permissions:
  id-token: write

jobs:
  promote-app-version:
    runs-on: ubuntu-latest
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f
        id: octo-sts
        with:
          scope: kartverket/bygning-apps
          identity: bygning

      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          repository: kartverket/bygning-apps
          ref: main
          token: ${{ steps.octo-sts.outputs.token }}

      - name: Promote version, commit and push
        run: |
          git config --global user.email "bygning@kartverket.no"
          git config --global user.name "Bygning CI"
          git pull

          FROM_APPLICATION="${{ inputs.cluster_from }}/${{ inputs.namespace_from }}/${{ inputs.application_name }}"
          TO_APPLICATION="${{ inputs.cluster_to }}/${{ inputs.namespace_to }}/${{ inputs.application_name }}"

          IMAGE_VERSION="$(cat "env/${FROM_APPLICATION}-version")"

          if [ "${{ inputs.allow_unsafe_deploy }}" = "false" ]; then

              # Check if image version contains a semantic version pattern
              # The pattern is a simplified version which allows any -suffix, even if non-standard
              if ! [[ "$IMAGE_VERSION" =~ ^.+:v(\d|[1-9]\d+)\.(\d|[1-9]\d+)\.(\d|[1-9]\d+)(-\S+)?@.+$ ]]; then
                  echo "Error: Image version ${IMAGE_VERSION} does not contain required version format v#.#.#[-suffix]"
                  exit 1
              fi
          fi

          cp env/"$FROM_APPLICATION"-version env/"$TO_APPLICATION"-version

          git add --update .
          git commit -m "Promote application ${{ inputs.application_name }} from '$FROM_APPLICATION' to '$TO_APPLICATION'"
          git push
